### PR TITLE
Add Motifs formalism

### PR DESCRIPTION
**Pull request by cgravill**
Hillel this has the Motifs formalism that you were after using.

### CODE REVIEW

**Comment by kuglerh** [comment]
Great, Builds properly on my machine

**Comment by cgravill** [comment]
Feel free to approve once you're happy

**Comment by kuglerh** [comment]
Notebooks work properly on Windows

**Review by kuglerh — APPROVED** [review]
Motifs and RE:SIN notebooks work  well on Windows

**Review by kuglerh — APPROVED** [review]

**Review by kuglerh — APPROVED** [review]

**Comment by cgravill** [comment]
Are you happy @byyordanov ? I'll assume yes if I don't hear otherwise.

**Review by byoyo — APPROVED** [review]

**Pull request merged**
